services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "8000:8000"
    command: "uv run uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../src/:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge
