services:
  web:
    image: fast-api
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    command: "uv run uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000"
#    command: "uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../src/:/app/src/
    networks:
      - backend

networks:
  backend:
    driver: bridge
